#:schema node_modules/wrangler/config-schema.json

name = "getkkul-shopping-main"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Pages 배포 설정
pages_build_output_dir = ".vercel/output/static"

# 환경변수
[vars]
NODE_ENV = "production"
NEXT_PUBLIC_TOSS_CLIENT_KEY = "live_gck_ex6BJGQOVDW0aeEX0X5X3W4w2zNb"
NEXT_PUBLIC_TOSS_VARIANT_KEY = "getkkul-live-toss"
NEXT_PUBLIC_TOSS_SUCCESS_URL = "https://www.getkkul.com/payment/success"
NEXT_PUBLIC_TOSS_FAIL_URL = "https://www.getkkul.com/payment/fail"
NEXT_PUBLIC_FREE_SHIPPING_THRESHOLD = "29000"
NEXT_PUBLIC_TOSS_API_URL = "https://api.tosspayments.com"

